## 基于感知器的与运算实现
这段代码实现了一个简单的感知器，用于解决与运算问题。代码中定义了一个感知器类，包含初始化、激活函数、预测和训练等方法。在主函数中，创建了一个感知器实例，然后使用输入数据和期望输出进行训练，最后对输入数据进行预测并输出结果。

In [14]:
# 导入 numpy 库，用于处理数组和矩阵
import numpy as np

### 定义感知器类
1.在训练过程中，权重会不断更新。每次迭代时，代码会输出当前的权重值。这些权重值会逐渐收敛，使得感知器能够正确地进行与运算。
⒉训练完成后，输出最终的权重值。这个权重值包括两个输入权重和一个偏置项权重。


In [15]:
class Perceptron(object):
    # 初始化感知器，设置输入大小、学习率和迭代次数
    def __init__(self, input_size, lr=1, epochs=100):
        self.W = np.zeros(input_size+1)  # 初始化权重，加1是为了包含偏置项
        self.epochs = epochs  # 设置迭代次数
        self.lr = lr  # 设置学习率

    # 定义激活函数，当输入大于等于0时返回1，否则返回0
    def activation(self, x):
        return 1 if x >= 0 else 0

    # 预测函数，计算输入和权重的点积，然后通过激活函数得到预测结果
    def predict(self, x):
        z = self.W.T.dot(x)
        a = self.activation(z)
        return a

    # 训练函数，根据输入数据和期望输出调整权重
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                x = np.insert(X[i], 0, 1)  # 在输入数据前插入1，用于计算偏置项
                y = self.predict(x)  # 预测结果
                err = d[i] - y  # 计算误差
                self.W = self.W + self.lr * err * x  # 更新权重
                print(self.W)

### 主函数

In [18]:
if __name__ == '__main__':
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # 输入数据
    y = np.array([0, 0, 0, 1])  # 期望输出（与运算）

    # 创建感知器实例
    perceptron = Perceptron(input_size=2)
    # 训练感知器
    perceptron.fit(X, y)
    # 输出训练后的权重
    print(perceptron.W)
    # 对输入数据进行预测并输出结果
    for x in X:
        x = np.insert(x, 0, 1)
        y_pre = perceptron.predict(x)
        print('%s and %s = %s' % (x[1], x[2], y_pre))

[-1.  0.  0.]
[-1.  0.  0.]
[-1.  0.  0.]
[0. 1. 1.]
[-1.  1.  1.]
[-2.  1.  0.]
[-2.  1.  0.]
[-1.  2.  1.]
[-1.  2.  1.]
[-2.  2.  0.]
[-3.  1.  0.]
[-2.  2.  1.]
[-2.  2.  1.]
[-2.  2.  1.]
[-3.  1.  1.]
[-2.  2.  2.]
[-2.  2.  2.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2.  1.]
[-3.  2. 